// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qscyapmuiqaijvuitlyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzY3lhcG11aXFhaWp2dWl0bHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDk3ODMsImV4cCI6MjA2ODQyNTc4M30.Z5ZKQiYooi4M2hxHMs8I7B7gPhrZzWJv69L7AUKtxYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});